libeffects: fix arithmetic on a pointer to void
Use char* instead of void* for this
pointer arithmetic. Fixes the following:

error: arithmetic on a pointer to void
pReplyData += size;
~~~~~~~~~~ ^

Change-Id: Iac9e5718d310cdb006c271af1a1fb4e7acefbaac